### ISSUE TITLE
Change it for custom post type doesn't work

### ISSUE THREAD

**Issue by g1on3v** [aktarujjman/ajax-filter-posts#1]
First - TOP plugin! ;)
I'm trying to change it to work for custom post type, but the category filter doesn't work.
I changed all 'post_type' => 'projects' and $taxonomy = 'projects_category';
It displays all correct, pagination work, but when I click a category to filter --> No Posts Found.

**Comment by akshuvo** [comment]
we're working on it. Thanks

**Comment by akshuvo** [comment]
This issue is fixed on gridmaster branch
